name: interview
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment: 
  sdk: '>=2.16.1 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  widgetbook: 2.0.5-beta
  auto_size_text: 3.0.0
  flutter_svg: ^1.0.3
dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_lints: ^1.0.0
flutter: 
  uses-material-design: true
  assets: 
    - packages/interview/assets/images/viewed.svg
    - packages/interview/assets/images/ellipse399.png
    - packages/interview/assets/images/intersect.png
    - packages/interview/assets/images/ellipse155.png
    - packages/interview/assets/images/image.svg
    - packages/interview/assets/images/play.svg
    - packages/interview/assets/images/vector.svg
    - packages/interview/assets/images/verificationanimation1.png
    - packages/interview/assets/images/discord61.svg
    - packages/interview/assets/images/battery.svg
    - packages/interview/assets/images/wifi.png
    - packages/interview/assets/images/mobilesignal.png
    - packages/interview/assets/images/time.svg
    - packages/interview/assets/images/activeglow.png
    - packages/interview/assets/images/homeindicator.png
    - packages/interview/assets/images/vector64.svg
    - packages/interview/assets/images/vector63.svg
    - packages/interview/assets/images/vector65.svg
    - packages/interview/assets/images/ellipse166.svg
    - packages/interview/assets/images/vector61.svg
    - packages/interview/assets/images/vector62.svg
    - packages/interview/assets/images/ellipse161.png
    - packages/interview/assets/images/ellipse160.png
    - packages/interview/assets/images/ellipse159.svg
